version: '3.1'

services:
    wordpress:
        depends_on:
        - db
        image: wordpress:latest
        restart: on-failure
        ports:
            - 5555:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpressAPI
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: mariadb
        restart: on-failure
        environment:
            MYSQL_DATABASE: wordpressAPI
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        
        volumes:
            - ./datas:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
